# Assignment 6

*(Due Saturday, October 26, 2019 at noon.)*

**1)** Below, paste the code needed to import and clean your file from the `../dataset` directory in your repository, then save the result to a new file. I should be able to run the code in this notebook and get my own copy of your cleaned, processed data.

**Note:** Your assignment file will be publicly accessible on Github. If your dataset is private, don't print anything confidential in this assignment.

In [70]:
import numpy as np
import pandas as pd
import datetime as dt

bostoncrime = pd.read_excel('../dataset/crime1yr.xlsx', sheet_name=0)
bostoncrime = bostoncrime.drop(["YEAR", "MONTH", "HOUR"], axis=1)
bostoncrime = bostoncrime.fillna('-')
pd.to_datetime(bostoncrime.OCCURRED_ON_DATE)
bostoncrime['DATE'] = [d.date() for d in bostoncrime['OCCURRED_ON_DATE']]
bostoncrime['DAY'] = pd.DatetimeIndex(bostoncrime['DATE']).day
bostoncrime['MONTH'] = pd.DatetimeIndex(bostoncrime['DATE']).month
bostoncrime['YEAR'] = pd.DatetimeIndex(bostoncrime['DATE']).year
bostoncrime['ORDINAL_DAY'] = [d.toordinal() for d in bostoncrime['DATE']]
bostoncrime['TIME'] = [d.time() for d in bostoncrime['OCCURRED_ON_DATE']]
bostoncrime = bostoncrime.drop(["OCCURRED_ON_DATE"], axis=1)

#Save your file (change the name if necessary).
bostoncrime.to_excel('../dataset/cleancrimeboston.xlsx')

In [71]:
bostoncrime

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,DAY_OF_WEEK,UCR_PART,STREET,Lat,Long,Location,DATE,DAY,MONTH,YEAR,ORDINAL_DAY,TIME
0,I182070933,724,Auto Theft,AUTO THEFT,B2,330,-,Monday,Part One,NORMANDY ST,42.3061,-71.0827,"(42.30607218, -71.08273260)",2018-09-03,3,9,2018,736940,21:25:00
1,I182070940,3114,Investigate Property,INVESTIGATE PROPERTY,D4,272,-,Monday,Part Three,NEWCOMB ST,42.3342,-71.0787,"(42.33418175, -71.07866441)",2018-09-03,3,9,2018,736940,21:16:00
2,I182070936,3820,Motor Vehicle Accident Response,M/V ACCIDENT INVOLVING PEDESTRIAN - INJURY,C11,398,-,Monday,Part Three,TALBOT AVE,42.2902,-71.0716,"(42.29019621, -71.07159012)",2018-09-03,3,9,2018,736940,21:09:00
3,I182070938,3114,Investigate Property,INVESTIGATE PROPERTY,B3,421,-,Monday,Part Three,DELHI ST,42.2754,-71.0904,"(42.27536542, -71.09036101)",2018-09-03,3,9,2018,736940,21:05:00
4,I182070931,301,Robbery,ROBBERY - STREET,C6,177,-,Monday,Part One,MASSACHUSETTS AVE,42.3315,-71.0709,"(42.33152148, -71.07085307)",2018-09-03,3,9,2018,736940,20:48:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98048,I172076776,3802,Motor Vehicle Accident Response,M/V ACCIDENT - PROPERTY Â DAMAGE,A7,27,-,Monday,Part Three,SUMNER ST,42.3697,-71.0416,"(42.36967378, -71.04155054)",2017-09-04,4,9,2017,736576,00:00:00
98049,I172073419,735,Auto Theft Recovery,RECOVERED - MV RECOVERED IN BOSTON (STOLEN OUT...,E13,912,-,Monday,Other,CENTRE ST,42.3228,-71.101,"(42.32283759, -71.10096723)",2017-09-04,4,9,2017,736576,00:00:00
98050,I172073338,3115,Investigate Person,INVESTIGATE PERSON,E13,574,-,Monday,Part Three,WASHINGTON ST,42.3097,-71.1043,"(42.30971857, -71.10429432)",2017-09-04,4,9,2017,736576,00:00:00
98051,I172073330,2647,Other,THREATS TO DO BODILY HARM,B2,309,-,Monday,Part Two,MARTIN LUTHER KING JR BLV,42.3186,-71.0841,"(42.31860134, -71.08405792)",2017-09-04,4,9,2017,736576,00:00:00
98052,I172073330,3125,Warrant Arrests,WARRANT ARREST,B2,309,-,Monday,Part Three,MARTIN LUTHER KING JR BLV,42.3186,-71.0841,"(42.31860134, -71.08405792)",2017-09-04,4,9,2017,736576,00:00:00

**2)** A brief survey: Have you taken an introductory statistics course, and if so, do you remember much from it? For example,

* Can you articulate the null hypotheses for the questions you formulated last week involving your data? 
* Do you know what a t-test is for?
* Do you know what a *p* value represents?
* Do you know what standard deviation is, and how it's calculated?

I have taken an intro stats course

Null hypotheses
1. There is no day with a significantly higher crime rate.
2. There was no offence committed significantly higher than the others.
3. No district reported a significantly higher crime rate.

A t-test is used to see if there is a significant difference between the mean of two different groups or populations.
A p-value is used to test data to either support or reject the null hypothesis.
Standard deviation is the average difference between the individual values and the mean. Standard deviation in this context is calculated by 1. finding the mean of the numbers 2. subtracting the mean from the number and squaring teh result 3. find the mean of the squared differences and finally 4. take the square root of that

#### Submitting

In the Terminal (Mac) or Git Bash (Windows):

`git commit -a -m 'Assignment 6 completed'`  
`git push`

### Reading

1. [_Python for Data Analysis_](https://uri-primo.hosted.exlibrisgroup.com/permalink/f/10nopmq/01URI_ALMA51209454630002396):
    * Section 7.3
    * Chapter 10